[package]
name = "Inflector"
version = "0.1.4"
authors = ["Josh Teeter<joshteeter@gmail.com>"]
exclude = [".travis.yml", ".gitignore"]
readme = "README.md"
repository = "https://github.com/whatisinternet/inflector"
documentation = "https://github.com/whatisinternet/inflector"
homepage = "https://github.com/whatisinternet/inflector"
license="BSD-2-Clause"
description = """
Adds String based inflections for Rust. Snake, kebab, camel, sentence, class, title, upper, and lower cases as well as ordinalize, deordinalize, demodulize, and foreign key are supported as both traits and pure functions acting on String types.
"""
keywords = ["string", "case", "camel", "snake", "inflection"]


[lib]
crate_type = ["dylib", "rlib"]
name = "inflector"
path = "src/lib.rs"

[dependencies]
regex = "0.1.41"
