[package]
name = "inflector"
version = "0.1.0"
authors = ["Josh teeter<joshteeter@gmail.com>"]

[lib]
crate_type = ["dylib", "rlib"]
name = "inflector"
path = "src/lib.rs"

[dependencies]
regex = "0.1.8"
